/**
 * Lab workflow numeric configuration and UI constants.
 */

export const LAB_CONFIG = {
  MAX_RETEST_ATTEMPTS: 3,
  MAX_RECOLLECTION_ATTEMPTS: 3,
  SEARCH_DEBOUNCE_MS: 300,
  DEFAULT_TEXTAREA_ROWS: 2,
  REJECTION_TEXTAREA_ROWS: 3,
  PARAMETER_PREVIEW_LIMIT: 5,
  TAB_COUNT_REFRESH_MS: 30000,
  COMPACT_RESULT_GRID_LIMIT: 8,
  POPOVER_OFFSET: 8,
  MODAL_SIZE_DEFAULT: '3xl' as const,
  MODAL_SIZE_LARGE: '4xl' as const,
  VALIDATION_ERROR_DISPLAY_MS: 3000,
  QUEUE_AGE_WARNING_HOURS: 4,
  QUEUE_AGE_CRITICAL_HOURS: 8,
} as const;
