import React, { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '@/hooks';
import {
  usePatientsList,
  usePatientSearch,
  useActiveTests,
  useTestSearch,
  useCreateOrder,
  useInvalidateOrders,
} from '@/hooks/queries';
import { SectionContainer, Badge, Button } from '@/shared/ui';
import { formatCurrency } from '@/utils';
import { displayId } from '@/utils/id-display';
import type { Order, OrderTest } from '@/types';
import toast from 'react-hot-toast';
import { logger } from '@/utils/logger';
import { PatientSelect as PatientSelector } from './PatientSelect';
import { TestSelect as TestSelector } from './TestSelect';
import { OrderForm as OrderDetailsForm } from './OrderForm';
import { useOrderForm } from './useOrderForm';

export const CreateOrder: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { currentUser } = useAuth();

  const preselectedPatientId = searchParams.get('patientId');
  const [selectedPatientId, setSelectedPatientId] = useState<string>(preselectedPatientId || '');
  const [patientSearch, setPatientSearch] = useState('');
  const [testSearch, setTestSearch] = useState('');

  // Use TanStack Query hooks (after state declarations)
  const { patients, isLoading: patientsLoading } = usePatientsList();
  const { results: filteredPatientsFromSearch } = usePatientSearch(patientSearch);
  const { tests: activeTests, isLoading: testsLoading } = useActiveTests();
  const { results: filteredTestsFromSearch } = useTestSearch(testSearch);
  const createOrderMutation = useCreateOrder();
  const { invalidateAll: invalidateOrders } = useInvalidateOrders();

  const { formData, errors, isSubmitting, setIsSubmitting, updateField, validate, setError } =
    useOrderForm();

  if (patientsLoading || testsLoading) {
    return <div>Loading...</div>;
  }

  const numericPatientId = selectedPatientId
    ? typeof selectedPatientId === 'string'
      ? parseInt(selectedPatientId, 10)
      : selectedPatientId
    : null;
  const selectedPatient = numericPatientId
    ? patients.find(p => p.id === numericPatientId)
    : undefined;

  const filteredPatients = patientSearch ? filteredPatientsFromSearch.slice(0, 5) : [];

  const filteredTests = testSearch
    ? filteredTestsFromSearch.slice(0, 10)
    : activeTests.slice(0, 10);

  const totalPrice = formData.selectedTests.reduce((sum, testCode) => {
    const test = activeTests.find(t => t.code === testCode);
    return sum + (test?.price || 0);
  }, 0);

  const toggleTest = (testCode: string) => {
    updateField(
      'selectedTests',
      formData.selectedTests.includes(testCode)
        ? formData.selectedTests.filter(t => t !== testCode)
        : [...formData.selectedTests, testCode]
    );
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!selectedPatient) {
      setError('patient', 'Please select a patient');
      toast.error('Please select a patient');
      return;
    }

    if (!validate()) {
      toast.error('Please fix the errors in the form');
      return;
    }

    setIsSubmitting(true);

    try {
      // IDs will be generated by the backend
      const orderTests: OrderTest[] = formData.selectedTests.map(testCode => {
        const test = activeTests.find(t => t.code === testCode);
        if (!test) throw new Error(`Test ${testCode} not found`);

        return {
          testCode: test.code,
          testName: test.name,
          sampleType: test.sampleType,
          status: 'pending',
          priceAtOrder: test.price,
          results: null,
        };
      });

      const newOrder: Omit<Order, 'orderId'> & { orderId?: number } = {
        orderId: 0, // Temporary - backend will assign real ID
        patientId:
          typeof selectedPatient.id === 'string'
            ? parseInt(selectedPatient.id, 10)
            : selectedPatient.id,
        patientName: selectedPatient.fullName,
        orderDate: new Date().toISOString(),
        referringPhysician: formData.referringPhysician.trim() || undefined,
        tests: orderTests,
        priority: formData.priority,
        clinicalNotes: formData.clinicalNotes.trim() || undefined,
        totalPrice,
        paymentStatus: 'unpaid',
        overallStatus: 'ordered',
        createdBy:
          typeof currentUser?.id === 'string' ? parseInt(currentUser.id, 10) : currentUser?.id || 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      // Create order - mutation will handle cache invalidation
      const createdOrder = await createOrderMutation.mutateAsync(newOrder as Order);

      // Invalidate orders cache to ensure fresh data
      await invalidateOrders();

      const actualOrderId = createdOrder.orderId;

      toast.success(`Order ${displayId.order(actualOrderId)} created successfully!`);
      navigate(`/orders/${actualOrderId}`);
    } catch (error) {
      logger.error('Error creating order', error instanceof Error ? error : undefined);
      const message =
        error instanceof Error ? error.message : 'Failed to create order. Please try again.';
      toast.error(message);
      setIsSubmitting(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto">
      <form onSubmit={handleSubmit} className="space-y-6">
        <PatientSelector
          selectedPatient={selectedPatient || null}
          patientSearch={patientSearch}
          onPatientSearchChange={setPatientSearch}
          filteredPatients={filteredPatients}
          onSelectPatient={patient => {
            setSelectedPatientId(patient.id.toString());
            setPatientSearch('');
          }}
          onClearSelection={() => {
            setSelectedPatientId('');
            setPatientSearch('');
          }}
          error={errors.patient}
        />

        <TestSelector
          selectedTests={formData.selectedTests}
          testSearch={testSearch}
          onTestSearchChange={setTestSearch}
          filteredTests={filteredTests}
          onToggleTest={toggleTest}
          totalPrice={totalPrice}
          error={errors.tests}
        />

        <OrderDetailsForm
          referringPhysician={formData.referringPhysician}
          priority={formData.priority}
          clinicalNotes={formData.clinicalNotes}
          onReferringPhysicianChange={value => updateField('referringPhysician', value)}
          onPriorityChange={value => updateField('priority', value)}
          onClinicalNotesChange={value => updateField('clinicalNotes', value)}
        />

        <SectionContainer title="Order Summary">
          <div className="space-y-3">
            <div className="flex justify-between text-sm">
              <span className="text-gray-600">Patient:</span>
              <span className="font-medium">{selectedPatient?.fullName || 'Not selected'}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-600">Number of Tests:</span>
              <span className="font-medium">{formData.selectedTests.length}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-600">Priority:</span>
              <Badge
                variant={
                  formData.priority === 'stat'
                    ? 'danger'
                    : formData.priority === 'urgent'
                      ? 'warning'
                      : 'info'
                }
              >
                {formData.priority.toUpperCase()}
              </Badge>
            </div>
            <div className="border-t pt-3 flex justify-between">
              <span className="font-semibold text-gray-900">Total Amount:</span>
              <span className="font-bold text-xl text-sky-600">{formatCurrency(totalPrice)}</span>
            </div>
          </div>
        </SectionContainer>

        <div className="flex items-center justify-end gap-3">
          <Button
            type="button"
            variant="cancel"
            showIcon={false}
            onClick={() => navigate('/orders')}
          >
            Cancel
          </Button>
          <Button type="submit" variant="create" isLoading={isSubmitting} disabled={isSubmitting}>
            {isSubmitting ? 'Creating Order...' : 'Create Order'}
          </Button>
        </div>
      </form>
    </div>
  );
};
