/** Base, priority, gender, relationships, medical, user roles → badge color */
import type { BadgeColor } from '@/components/primitives/types';

export const MISC_COLOR_MAP: Record<string, BadgeColor> = {
  default: 'neutral',
  primary: 'primary',
  secondary: 'neutral',
  outline: 'neutral',
  ghost: 'neutral',
  error: 'danger',
  low: 'neutral',
  medium: 'info',
  high: 'warning',
  urgent: 'danger',
  male: 'info',
  female: 'pink',
  friend: 'purple',
  child: 'info',
  parent: 'success',
  sibling: 'danger',
  spouse: 'warning',
  'chronic-condition': 'orange',
  medication: 'info',
  allergy: 'danger',
  surgery: 'purple',
  administrator: 'danger',
  receptionist: 'info',
  'lab-technician': 'success',
  'lab-technician-plus': 'purple',
  pathologist: 'purple',
};
